### ISSUE TITLE
Doesn't work with "create-react-app --template typescript"

### ISSUE THREAD

**Issue by euaaron** [mhanki/Clean-React#1]
I loved your project! But I just work with Typescript...

It would be cool to verify if the file extension of the generated files are in `.js`, `.jsx`, `.tsx` or `.ts` format and keep their original extensions. By now, the Clean-React CLI is adding an `index.js` and an `App.js` file to the `src/` dir and keeping my originals `index.tsx` and `App.tsx`. Anyways... everything works fine after deleting the original files and renaming the new `.js` files to `.tsx`.

Your project seens to become a huge utility for the React community. Hope it keeps growing and becoming more compatible with more templates rather then only with the default! Maybe even with other generators like create-next-app?

**Comment by mhanki** [comment]
Thank you so much for the feedback. It is truly appreciated!

You are right, as of now the tool only supports cleanup for the default create-react-app template, but TypeScript support and file type checks are in the works! :) I hope to release the new version by the end of the week.

I'd love for the project to be even more universally useful and support other templates and generators, it will just be a slow process, as I don't have a lot of time to do so. I'm always happy about contributions though, so if you want to tackle some of that, definitely go ahead! I'll try to add contribution guidelines and PR templates on the weekend as well.

Thanks again for the nice words. I'm afraid the npm download stats aren't very representative of how much a package actually is being used, especially after a new release, as there seem to be a [great number of bots etc.](https://blog.npmjs.org/post/92574016600/numeric-precision-matters-how-npm-download-counts-work.html) that push these numbers up quite a bit.. I had no idea! But I'm already super happy that it seems to be useful at least for some :)

I'll try to make sure it's useable with TypeScript as soon as possible, and again, if you have more ideas or want to contribute, feel free to reach out again!
